# dev-ingest-v2 - ReportGrid dev ingest service (v2)
#
#

description "dev-ingest-v2 - ReportGrid dev ingest service (v2)"

start on runlevel [2345]
stop on runlevel [06]

respawn

pre-start script
  [ -d /var/run/precog ] || install -m 755 -o precog -g precog -d /var/run/precog
end script

script
  if [ -f /etc/default/ingest-v2 ]; then . /etc/default/ingest-v2; fi
  su precog -s "/bin/bash" -c "/usr/bin/java $JAVA_OPTS -Dlogback.configurationFile=/etc/precog/ingest-v2.logging.xml -jar /usr/share/java/ingest-v2.jar --configFile /etc/precog/ingest-v2.conf >> /var/log/precog/ingest-v2.stdout.log 2>&1"
end script

post-start script
  echo `status ingest-v2 | egrep -o '[0-9]+$' | head -n1` > /var/run/precog/ingest-v2.pid
end script
