# jobs-v1-b - ReportGrid beta auth service (v1/backup)
#
#

description "jobs-v1-b - ReportGrid beta jobs service (v1/backup)"

start on runlevel [2345]
stop on runlevel [06]

respawn

pre-start script
  [ -d /var/run/precog ] || install -m 755 -o precog -g precog -d /var/run/precog
end script

script
  if [ -f /etc/default/jobs-v1-b ]; then . /etc/default/jobs-v1-b; fi
  su precog -s "/bin/bash" -c "/usr/bin/java $JAVA_OPTS -Dlogback.configurationFile=/etc/precog/jobs-v1-b.logging.xml -jar /usr/share/java/jobs-v1-b.jar --configFile /etc/precog/jobs-v1-b.conf >> /var/log/precog/jobs-v1-b.stdout.log 2>&1"
end script

post-start script
  echo `status jobs-v1-b | egrep -o '[0-9]+$' | head -n1` > /var/run/precog/jobs-v1-b.pid
end script
